intro: This simple dash helps familiarise cogstack indexes to users. 
instructions: Please select the number of documents (i.e., rows) that you want to be read into as a sample.
start2: See here how the data looks like!
hellotext: Teddy build this to make his life easier.
learnings: |
    ### Learnings / Bugs 
    -  For example, Elastic Search has a data type "text" vs "keyword". Keywords are almost like a category but not quite. It is not broken down
            any further and analysed by Elastic Search. Elastic Search breaks down **text**. Therefore, you can use fuzzy matching for text column but not for keyword columns.
            See more here [Text vs Keyword by Elastic.co](https://www.elastic.co/blog/strings-are-dead-long-live-strings)
            
    - Elasticsearch API for large searches need scroll function
    - Streamlit converts pandas to pyarrow. there is an error regarding that. i will fix later.
    - Elastic search column names are not columns but called "fields".
    - future features [use nltk or spacy --spacy has some issues with version conflict. nltk has difficulty downloading onto streamlit environment to remove stop words]
    - append column data types and if keywrod or categorical, append min  max, value counts etc


all_cols_query:
  size: "__PLACEHOLDER__"
  query: {"match_all":{}}


kw_query: 
  size: 0
  aggs: {
    "top_terms":{
      "terms": {
        "field": field,
        "size":10
      }
    }
  }

escapekwlist: 
  - activity_VisitNumber
  - patient_MRN
  - patient_NhsNumber
  - patient_SourceId
  - patient_HospitalNumber
  - patient_HospitalNumber_GSTT
  - id
  - document_FileName
  - document_AttId
  - document_OriginalFilePath
  - document_SourceId