services:
  vllm:
    image: vllm/vllm-openai:latest
    container_name: ${CONTAINER_NAME}
    runtime: nvidia
    ipc: host
    ports:
      - "${PORT}:8000"
    volumes:
      - ${MODEL_PATH}:/model
    command: >
      --model /model
      --dtype bfloat16
      --gpu-memory-utilization 0.95
      --swap-space 8
      --enable-prefix-caching
      --enforce-eager
      --tensor-parallel-size 1
      --max-num-seqs 1
      --max-num-batched-tokens 12000
      --max-model-len 12000
      --disable-continuous-batching
      --block-size 16
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - bioext_network

networks:
  bioext_network:
    external: true